In [ ]:
import pandas as pd
import numpy as np



: 

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
import joblib

In [5]:
df = pd.read_csv("cleaned_dataset.csv")

In [6]:
print(df.head())
print(df.info())

   id  gender   age           city profession  academic_pressure  \
0   2    male  33.0  visakhapatnam    student                5.0   
1   8  female  24.0      bangalore    student                2.0   
2  26    male  31.0       srinagar    student                3.0   
3  30  female  28.0       varanasi    student                3.0   
4  32  female  25.0         jaipur    student                4.0   

   work_pressure  cgpa  study_satisfaction  job_satisfaction  sleep_duration  \
0            0.0  8.97                 2.0               0.0             NaN   
1            0.0  5.90                 5.0               0.0             NaN   
2            0.0  7.03                 5.0               0.0             NaN   
3            0.0  5.59                 2.0               0.0             NaN   
4            0.0  8.13                 3.0               0.0             NaN   

  dietary_habits   degree have_you_ever_had_suicidal_thoughts_?  \
0        healthy  b.pharm                  

In [7]:
if 'ID' in df.columns:
    df = df.drop('ID', axis=1)

# Fill missing values (simple approach)
df = df.ffill()

# Encode categorical columns
label_encoders = {}

for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le


C:\Users\KURT\AppData\Local\Temp\ipykernel_2144\3312826337.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:


In [ ]:
target_column = "Depression"

target_column = "depression"

X = df.drop(target_column, axis=1)
y = df[target_column]
y = df[target_column]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

results = {}

for name, model in models.items():
    # drop columns that are entirely missing
    all_nan_cols = X_train.columns[X_train.isna().all()]
    if len(all_nan_cols):
        X_train = X_train.drop(columns=all_nan_cols)
        X_test = X_test.drop(columns=all_nan_cols)

    # impute remaining missing values
    imputer = SimpleImputer(strategy="median")
    X_train = pd.DataFrame(imputer.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
    X_test = pd.DataFrame(imputer.transform(X_test), columns=X_test.columns, index=X_test.index)

    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000),
        "Decision Tree": DecisionTreeClassifier(),
        "Random Forest": RandomForestClassifier()
    }

    results = {}

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        print(f"\n{name}")
        print("Accuracy:", accuracy_score(y_test, y_pred))
        print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
        print("Classification Report:\n", classification_report(y_test, y_pred))

        results[name] = accuracy_score(y_test, y_pred)
    y_pred = model.predict(X_test)

    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))

    results[name] = accuracy_score(y_test, y_pred)


c:\Users\KURT\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(



Logistic Regression
Accuracy: 0.8317505823329152
Confusion Matrix:
 [[1820  523]
 [ 416 2822]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.78      0.79      2343
           1       0.84      0.87      0.86      3238

    accuracy                           0.83      5581
   macro avg       0.83      0.82      0.83      5581
weighted avg       0.83      0.83      0.83      5581


Decision Tree
Accuracy: 0.7541659200860061
Confusion Matrix:
 [[1683  660]
 [ 712 2526]]
Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.72      0.71      2343
           1       0.79      0.78      0.79      3238

    accuracy                           0.75      5581
   macro avg       0.75      0.75      0.75      5581
weighted avg       0.76      0.75      0.75      5581


Random Forest
Accuracy: 0.8297796093889984
Confusion Matrix:
 [[1832  511]
 [ 439 2799]]
Classification Report:

c:\Users\KURT\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(



Logistic Regression
Accuracy: 0.8317505823329152
Confusion Matrix:
 [[1820  523]
 [ 416 2822]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.78      0.79      2343
           1       0.84      0.87      0.86      3238

    accuracy                           0.83      5581
   macro avg       0.83      0.82      0.83      5581
weighted avg       0.83      0.83      0.83      5581


Decision Tree
Accuracy: 0.7518365884250134
Confusion Matrix:
 [[1676  667]
 [ 718 2520]]
Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.72      0.71      2343
           1       0.79      0.78      0.78      3238

    accuracy                           0.75      5581
   macro avg       0.75      0.75      0.75      5581
weighted avg       0.75      0.75      0.75      5581


Random Forest
Accuracy: 0.8313922236158394
Confusion Matrix:
 [[1840  503]
 [ 438 2800]]
Classification Report:

c:\Users\KURT\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(



Logistic Regression
Accuracy: 0.8317505823329152
Confusion Matrix:
 [[1820  523]
 [ 416 2822]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.78      0.79      2343
           1       0.84      0.87      0.86      3238

    accuracy                           0.83      5581
   macro avg       0.83      0.82      0.83      5581
weighted avg       0.83      0.83      0.83      5581


Decision Tree
Accuracy: 0.7518365884250134
Confusion Matrix:
 [[1683  660]
 [ 725 2513]]
Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.72      0.71      2343
           1       0.79      0.78      0.78      3238

    accuracy                           0.75      5581
   macro avg       0.75      0.75      0.75      5581
weighted avg       0.75      0.75      0.75      5581


Random Forest
Accuracy: 0.8317505823329152
Confusion Matrix:
 [[1849  494]
 [ 445 2793]]
Classification Report:

In [ ]:
best_model_name = max(results, key=results.get)
best_model = models[best_model_name]

print("\nBest Model:", best_model_name)

joblib.dump(best_model, "best_model.pkl")
joblib.dump(label_encoders, "label_encoders.pkl")

print("Model saved successfully!")


Best Model: Logistic Regression
Model saved successfully!
